import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import { FiltersProvider } from "@/context/FiltersContext";
import GlobalFilters from "@/components/GlobalFilters";
import { Filter } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-white">
        <FiltersProvider>
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <GlobalFilters />
            <main className="p-6">{children}</main>
          </div>
        </div>
        </FiltersProvider>
      </body>
    </html>
  );
}